# 기반 이미지 선택 (Node.js 안정된 최신버전)
FROM node:20-alpine

# 애플리케이션 디렉토리 생성
WORKDIR /app

# PM2 글로벌 설치
RUN yarn global add pm2

# package.json 과 yarn.lock을 /app 디렉토리로 복사
COPY package.json yarn.lock ./

# 의존성 설치
RUN yarn install

# Domain 서버 코드만 복사
COPY src/domains ./domains
COPY src/middlewares ./middlewares
COPY src/utils ./utils
COPY logs ./logs

# Prisma 클라이언트 생성
COPY prisma ./prisma
RUN yarn prisma generate

# 애플리케이션 실행을 위한 포트 열기
EXPOSE 3000

# 애플리케이션 실행
CMD ["pm2-runtime", "src/domains/app.js"]