version: '3.8'
services:
    app:
        build: .
        environment:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            KAKAO_REDIRECT_URI: ${{ secrets.DEV_KAKAO_REDIRECT_URI }}
            CORS_ORIGIN: '*'
            SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
            REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
            ACCESS_TOKEN_LIFE: ${{ secrets.ACCESS_TOKEN_LIFE }}
            REFRESH_TOKEN_LIFE: ${{ secrets.REFRESH_TOKEN_LIFE }}
            CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        ports:
            - '3001:3000'
        command: ['yarn', 'dev']
