# name: Notify on Dev Push

# on:
#     push:
#         branches:
#             - dev

# jobs:
#     notify-slack:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Checkout
#               uses: actions/checkout@v3

#             - name: Send Slack Notification
#               uses: 8398a7/action-slack@v3
#               with:
#                   status: ${{ job.status }}
#                   fields: repo,commit,author,action,eventName,ref,workflow
#                   text: '🍫 New push to dev branch!'
#               env:
#                   SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
